# Generated by Django 2.0.4 on 2018-05-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0002_testdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.IntegerField(choices=[('Pending', 0), ('Accepted', 1), ('Wrong Answer', 2), ('Compile Error', 3), ('Time Limit Exceed', 4), ('Memory Limit Exceed', 5), ('Presentation Error', 6)], default=0)),
                ('time_cost', models.IntegerField(blank=True, null=True)),
                ('memory_cost', models.IntegerField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
        ),
    ]
