# Generated by Django 2.0.4 on 2018-05-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Wrong Answer'), (3, 'Compile Error'), (4, 'Time Limit Exceed'), (5, 'Memory Limit Exceed'), (6, 'Presentation Error')], default=0),
        ),
    ]
